/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.fortunewheelview;

import java.io.IOException;
import java.util.Iterator;
import java.util.Map;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.io.TiFileFactory;
import org.appcelerator.titanium.io.TiBaseFile;
import org.appcelerator.titanium.util.TiUIHelper;
import org.appcelerator.titanium.view.TiUIView;
import org.appcelerator.titanium.view.TiDrawableReference;
import org.appcelerator.titanium.TiBlob;

import com.myriadmobile.fortune.FortuneView;
import com.myriadmobile.fortune.FortuneItem;
import com.myriadmobile.fortune.GrooveListener;

import android.app.Activity;
import android.widget.LinearLayout;
import android.widget.LinearLayout.LayoutParams;

import java.util.HashMap;
import java.util.ArrayList;

import android.graphics.Bitmap;

@Kroll.proxy(creatableInModule = WheelViewModule.class)
public class WheelViewProxy extends TiViewProxy {
	// Standard Debugging variables
	public static final String LCAT = "WheelView";

	public TiUIWheelView mView;
	public String[] icons;
	public KrollDict attributes;
	FortuneView fortuneView;

	// Constructor
	public WheelViewProxy() {
		super();
		attributes = new KrollDict();
		attributes.put("centripetalPercent", .25f);
		attributes.put("distanceScale", 1f);
		attributes.put("flingable", true);
		attributes.put("frameRate", 40);
		attributes.put("friction", 5);

		attributes.put("grooves", true);
		attributes.put("minimumSize", .1f);
		attributes.put("notch", 90);
		attributes.put("spinSensitivity", 1f);
		attributes.put("selectScaleOffset", 1f);

		attributes.put("unselectScaleOffset", .8f);
		attributes.put("velocityClamp", 15);
		Log.d(LCAT, "WheelViewProxy");
	}

	@Override
	public TiUIView createView(Activity activity) {
		Log.d(LCAT, "createView inside ViewProxy ≠≠≠≠≠≠≠");
		mView = new TiUIWheelView(this);
		mView.getLayoutParams().autoFillsHeight = true;
		mView.getLayoutParams().autoFillsWidth = true;
		return mView;
	}

	@Kroll.method
	public int getSelectedIndex() {
		return fortuneView.getSelectedIndex();
	}

	@Kroll.method
	public void setSelectedItem(int ndx) {
		fortuneView.setSelectedItem(ndx);
	}

	@Kroll.method
	public int getTotalItems() {
		return fortuneView.getTotalItems();
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict args) {
		super.handleCreationDict(args);
		Log.d(LCAT, "handleCreationDict");
		if (args.containsKey("icons")) {
			icons = args.getStringArray("icons");
		}
		if (args.containsKey("wheelOptions")) {
			KrollDict options = args.getKrollDict("wheelOptions");
			Log.d(LCAT, "There are options:\n≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠ ");
			Log.d(LCAT, options.toString());
			for (Map.Entry<String, Object> entry : options.entrySet()) {
				Log.d(LCAT, entry.getKey() + "/" + entry.getValue());

			}
			/*
			 * attributes.put("centripetalPercent",
			 * options.getOrDefault("centripetalPercent", .25f)); Log.d(LCAT,
			 * attributes.toString()); attributes.put("distanceScale",
			 * options.getOrDefault("distanceScale", 1)); Log.d(LCAT,
			 * attributes.toString()); attributes .put("flingable",
			 * options.getOrDefault("flingable", true));
			 * attributes.put("frameRate", options.getOrDefault("frameRate",
			 * 40)); attributes.put("friction", options.getOrDefault("friction",
			 * 5));
			 * 
			 * attributes.put("grooves", options.getOrDefault("grooves", true));
			 * attributes.put("minimumSize", options.getOrDefault("minimumSize",
			 * .1f)); attributes.put("notch", options.getOrDefault("notch",
			 * 90)); attributes.put("spinSensitivity",
			 * options.getOrDefault("spinSensitivity", 1f));
			 * attributes.put("selectScaleOffset",
			 * options.getOrDefault("selectScaleOffset", 1f));
			 * 
			 * attributes.put("unselectScaleOffset",
			 * options.getOrDefault("unselectScaleOffset", .8f));
			 * attributes.put("velocityClamp",
			 * options.getOrDefault("velocityClamp", 15));
			 * Log.d(LCAT,"all options set");
			 */
		}
	}

	private class TiUIWheelView extends TiUIView {
		TiUIWheelView(final TiViewProxy proxy) {
			super(proxy);
			LayoutParams lp = new LayoutParams(LayoutParams.WRAP_CONTENT,
					LayoutParams.WRAP_CONTENT);
			LinearLayout container = new LinearLayout(proxy.getActivity());
			container.setLayoutParams(lp);
			// attributes are visible
			Log.d(LCAT, "TiUIWheelView");
			Log.d(LCAT, attributes.toString());
			fortuneView = new FortuneView(proxy.getActivity());
			fortuneView.setOptions(attributes);
			fortuneView.initSwipeControler();
			// adding of content into view:
			ArrayList<FortuneItem> list = new ArrayList<FortuneItem>();
			for (int i = 0; i < icons.length; i++) {
				list.add(new FortuneItem(getBitmapFromImage(icons[i])));
			}
			fortuneView.addFortuneItems(list);
			container.addView(fortuneView);
			// initiating listener(s)
			GrooveListener grooveListener = new GrooveListener() {
				@Override
				public void onGrooveChange(int index) {
					if (proxy.hasListeners("groovechanged")) {
						KrollDict payload = new KrollDict();
						payload.put("index", index);
						proxy.fireEvent("groovechanged", payload);
					} else {
						Log.e(LCAT, "cannot fireEvent 'ready' ");
					}
				}
			};
			fortuneView.setGrooveListener(grooveListener);
			setNativeView(container);
		}

		@Override
		public void processProperties(KrollDict d) {
			super.processProperties(d);
		}

		private Bitmap getBitmapFromImage(Object val) {
			if (val instanceof TiBlob) {
				TiDrawableReference ref = TiDrawableReference.fromBlob(
						proxy.getActivity(), (TiBlob) val);
				return ref.getBitmap();
			} else {
				return loadImageFromApplication((String) val);
			}
		}

		private Bitmap loadImageFromApplication(String imageName) {
			Bitmap bitmap = null;
			String url = null;
			try {
				url = resolveUrl(null, imageName);
				TiBaseFile file = TiFileFactory.createTitaniumFile(
						new String[] { url }, false);
				bitmap = TiUIHelper.createBitmap(file.getInputStream());
			} catch (IOException e) {
				Log.e(LCAT, " WheelView only supports local image files " + url);
				// file:///android_asset/Resources/[object TiFileProxy]
			}
			return bitmap;
		}
	}

}