/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.fortunewheelview;

import java.io.IOException;
import java.util.Map;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.common.AsyncResult;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiMessenger;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.io.TiFileFactory;
import org.appcelerator.titanium.io.TiBaseFile;
import org.appcelerator.titanium.util.TiUIHelper;
import org.appcelerator.titanium.view.TiUIView;
import org.appcelerator.titanium.view.TiDrawableReference;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiBlob;
import org.appcelerator.titanium.TiC;

import com.myriadmobile.fortune.FortuneView;
import com.myriadmobile.fortune.FortuneItem;
import com.myriadmobile.fortune.GrooveListener;

import android.app.Activity;
import android.os.Message;
import android.widget.LinearLayout;
import android.widget.LinearLayout.LayoutParams;

import java.util.ArrayList;

import android.graphics.Bitmap;

@Kroll.proxy(creatableInModule = WheelViewModule.class)
public class WheelViewProxy extends TiViewProxy {
	// Standard Debugging variables
	public static final String LCAT = "WheelView";

	public TiUIWheelView tiView;
	public String[] icons;
	public KrollDict attributes;
	FortuneView fortuneView;
	private static final int MSG_FIRST_ID = TiViewProxy.MSG_LAST_ID + 1;
	final private int MSG_SET = MSG_FIRST_ID + 100;
	final private int MSG_GET = MSG_FIRST_ID + 101;
	final private int MSG_TOTAL = MSG_FIRST_ID + 102;

	// Constructor
	public WheelViewProxy() {
		super();
		attributes = new KrollDict();
		attributes.put("centripetalPercent", .25f);
		attributes.put("distanceScale", 1f);
		attributes.put("flingable", true);
		attributes.put("frameRate", 40);
		attributes.put("friction", 5);

		attributes.put("grooves", true);
		attributes.put("minimumSize", .1f);
		attributes.put("notch", 90);
		attributes.put("spinSensitivity", 1f);
		attributes.put("selectScaleOffset", 1f);

		attributes.put("unselectScaleOffset", .8f);
		attributes.put("velocityClamp", 15);
		attributes.put("longpressTreshold", 1000);
		attributes.put("selectedIndex", 0);
	}

	@Override
	public TiUIView createView(Activity activity) {
		tiView = new TiUIWheelView(this);
		tiView.getLayoutParams().autoFillsHeight = true;
		tiView.getLayoutParams().autoFillsWidth = true;
		return tiView;
	}

	@Override
	public boolean handleMessage(Message msg) {
		AsyncResult result = null;
		switch (msg.what) {
		case MSG_GET: {
			result = (AsyncResult) msg.obj;
			handleSetSelectedIndex((int) msg.obj);
			result.setResult(null);
			return true;
		}
		case MSG_SET: {
			result = (AsyncResult) msg.obj;
			handleGetSelectedIndex();
			result.setResult(null);
			return true;
		}
		case MSG_TOTAL: {
			result = (AsyncResult) msg.obj;
			handleGetTotalItems();
			result.setResult(null);
			return true;
		}
		default: {
			return super.handleMessage(msg);
		}
		}
	}

	private int handleGetTotalItems() {
		return fortuneView.getTotalItems();
	}

	private int handleGetSelectedIndex() {
		if (fortuneView != null)
			return fortuneView.getSelectedIndex();
		Log.w(LCAT, "fortuneView is null");
		return 0;
	}

	private void handleSetSelectedIndex(int ndx) {
		if (fortuneView != null)
			fortuneView.setSelectedItem(ndx);
		else
			Log.w(LCAT, "fortuneView is null");
	}

	@Kroll.method
	public int getSelectedIndex() {
		if (TiApplication.isUIThread()) {
			return handleGetSelectedIndex();
		} else {
			return (int) TiMessenger.sendBlockingMainMessage(getMainHandler()
					.obtainMessage(MSG_GET));
		}
	}

	@Kroll.method
	public void setSelectedIndex(int ndx) {
		if (TiApplication.isUIThread()) {
			handleSetSelectedIndex(ndx);
		} else {
			TiMessenger.sendBlockingMainMessage(
					getMainHandler().obtainMessage(MSG_SET), ndx);
		}

	}

	@Kroll.method
	public int getTotalItems() {
		if (TiApplication.isUIThread()) {
			return handleGetTotalItems();
		} else {
			return (int) TiMessenger.sendBlockingMainMessage(getMainHandler()
					.obtainMessage(MSG_TOTAL));
		}
	}

	@Override
	public void handleCreationDict(KrollDict args) {
		super.handleCreationDict(args);
		if (args.containsKey(TiC.PROPERTY_IMAGES)) {
			icons = args.getStringArray(TiC.PROPERTY_IMAGES);
		}
		if (args.containsKey(TiC.PROPERTY_OPTIONS)) {
			KrollDict options = args.getKrollDict(TiC.PROPERTY_OPTIONS);
			for (Map.Entry<String, Object> entry : options.entrySet()) {
				attributes.put(entry.getKey(), entry.getValue());
			}
		}
	}

	private class TiUIWheelView extends TiUIView {
		private final class OnGrooveHandler implements GrooveListener {
			private final TiViewProxy proxy;

			private OnGrooveHandler(TiViewProxy proxy) {
				this.proxy = proxy;
			}

			@Override
			public void onGrooveChange(int index) {

				if (proxy.hasListeners("grovechanged")) {
					Log.d(LCAT, "grovechanged " + index);
					KrollDict payload = new KrollDict();
					payload.put("index", index);
					proxy.fireEvent("grovechanged", payload);
				} else {
					Log.e(LCAT, "cannot fireEvent 'ready' ");
				}
			}

			@Override
			public void onGrooveClicked(int index) {
				if (proxy.hasListeners("clicked")) {
					Log.d(LCAT, "onGrooveClicked");
					KrollDict payload = new KrollDict();
					payload.put("index", index);
					proxy.fireEvent("clicked", payload);
				} else {
				}

			}
		}

		TiUIWheelView(final TiViewProxy proxy) {
			super(proxy);
			LayoutParams lp = new LayoutParams(LayoutParams.WRAP_CONTENT,
					LayoutParams.WRAP_CONTENT);
			LinearLayout container = new LinearLayout(proxy.getActivity());
			container.setLayoutParams(lp);
			fortuneView = new FortuneView(proxy.getActivity());
			fortuneView.setOptions(attributes);
			fortuneView.initSwipeControler();
			ArrayList<FortuneItem> list = new ArrayList<FortuneItem>();
			for (int i = 0; i < icons.length; i++) {
				list.add(new FortuneItem(getBitmapFromImage(icons[i])));
			}
			fortuneView.addFortuneItems(list);
			container.addView(fortuneView);
			GrooveListener grooveListener = new OnGrooveHandler(proxy);
			fortuneView.setGrooveListener(grooveListener);
			setNativeView(container);
		}

		@Override
		public void processProperties(KrollDict d) {
			super.processProperties(d);
		}

		private Bitmap getBitmapFromImage(Object val) {
			if (val instanceof TiBlob) {
				TiDrawableReference ref = TiDrawableReference.fromBlob(
						proxy.getActivity(), (TiBlob) val);
				return ref.getBitmap();
			} else if (val instanceof String) {
				return loadImageFromApplication((String) val);
			} else {
				return null;
			}
		}

		private Bitmap loadImageFromApplication(String imageName) {
			Bitmap bitmap = null;
			String url = null;
			try {
				url = resolveUrl(null, imageName);
				TiBaseFile file = TiFileFactory.createTitaniumFile(
						new String[] { url }, false);
				bitmap = TiUIHelper.createBitmap(file.getInputStream());
			} catch (IOException e) {
				Log.e(LCAT, " WheelView only supports local image files " + url);
			}
			return bitmap;
		}
	}
}